version: "3.8"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - feshshop-infrastructure
    volumes:
      - mongo:/data/db

networks:
   feshshop-infrastructure:
    name: feshshop-infrastructure

volumes:
  mongo:
    driver: local