version: "3.8"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - feshshop-infrastructure
    volumes:
      - mongo:/data/db

  seq:
    image: datalust/seq
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - feshshop-infrastructure
    volumes: 
      - seq:/data

networks:
   feshshop-infrastructure:
    name: feshshop-infrastructure

volumes:
  mongo:
    driver: local